"use client";

import React, { useEffect, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { useAppStore } from "@/store/useAppStore";
import {
  Bookmark, ArrowRight, TrendingUp, Search,
  ArrowUpDown, Clock, Filter, Sparkles
} from "lucide-react";

const subscribeToHydration = () => () => {};

interface IdeaRecord {
  id: string;
  niche_score: number;
  target_user: string;
  problem: string;
  solution: string;
  stack: string[];
  is_saved: boolean;
  build_time_weeks: number;
  created_at?: string;
}

type SortKey = "newest" | "score" | "build_time";

export default function IdeasListPage() {
  const { token } = useAppStore();
  const [ideas, setIdeas] = useState<IdeaRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [sortBy, setSortBy] = useState<SortKey>("newest");
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const mounted = useSyncExternalStore(subscribeToHydration, () => true, () => false);

  useEffect(() => {
    if (mounted && !token) {
      window.location.href = "/auth/signin";
    }
  }, [mounted, token]);

  useEffect(() => {
    if (token) {
      const timeout = window.setTimeout(() => {
        api.get("/api/ideas")
          .then((data: IdeaRecord[]) => setIdeas(data))
          .catch(() => {})
          .finally(() => setLoading(false));
      }, 0);
      return () => window.clearTimeout(timeout);
    }
  }, [token]);

  const handleSaveToggle = async (ideaId: string, currentSaved: boolean) => {
    try {
      if (currentSaved) {
        await api.delete(`/api/ideas/${ideaId}/save`);
        setIdeas(ideas.map(i => i.id === ideaId ? { ...i, is_saved: false } : i));
      } else {
        await api.post(`/api/ideas/${ideaId}/save`);
        setIdeas(ideas.map(i => i.id === ideaId ? { ...i, is_saved: true } : i));
      }
    } catch {
      alert("Failed to update vault bookmark.");
    }
  };

  const filteredIdeas = ideas
    .filter(idea => {
      if (showSavedOnly && !idea.is_saved) return false;
      if (!searchQuery.trim()) return true;
      const q = searchQuery.toLowerCase();
      return (
        idea.target_user.toLowerCase().includes(q) ||
        idea.problem.toLowerCase().includes(q) ||
        idea.solution.toLowerCase().includes(q) ||
        idea.stack.some(s => s.toLowerCase().includes(q))
      );
    })
    .sort((a, b) => {
      switch (sortBy) {
        case "score": return b.niche_score - a.niche_score;
        case "build_time": return a.build_time_weeks - b.build_time_weeks;
        case "newest":
        default:
          return new Date(b.created_at || 0).getTime() - new Date(a.created_at || 0).getTime();
      }
    });

  if (!mounted || !token) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-black">
        <div className="flex h-10 w-10 animate-spin items-center justify-center rounded-full border-4 border-indigo-500 border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-9 flex flex-col justify-between gap-5 border-b border-white/[0.07] pb-8 sm:flex-row sm:items-end">
        <div>
          <p className="editorial-label">Workspace / ideas</p>
          <h1 className="mt-4 text-3xl font-extrabold tracking-[-0.045em] text-white sm:text-4xl">
            All SaaS Opportunities
          </h1>
          <p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">
            Browse, search, and manage every micro-SaaS idea generated by the multi-agent pipeline.
          </p>
        </div>
        <Link href="/dashboard/generate" className="premium-primary">
          Generate New <ArrowRight className="h-4 w-4" />
        </Link>
      </div>

      {/* Search & Filter Bar */}
      <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500 pointer-events-none" />
          <input
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search by target user, problem, solution, or stack..."
            className="w-full !pl-10 !pr-4 !py-2.5 text-sm rounded-xl"
          />
        </div>

        <div className="flex items-center gap-3">
          {/* Saved-only filter */}
          <button
            onClick={() => setShowSavedOnly(!showSavedOnly)}
            className={`flex items-center gap-2 rounded-xl border px-3.5 py-2 text-xs font-semibold transition-all ${
              showSavedOnly
                ? "border-amber-500/30 bg-amber-500/10 text-amber-400"
                : "border-white/5 bg-white/5 text-zinc-400 hover:text-white hover:border-white/15"
            }`}
          >
            <Bookmark className="h-3.5 w-3.5" />
            Saved Only
          </button>

          {/* Sort dropdown */}
          <div className="relative">
            <select
              value={sortBy}
              onChange={e => setSortBy(e.target.value as SortKey)}
              className="!py-2 !px-3 !pr-8 text-xs font-semibold rounded-xl appearance-none cursor-pointer"
            >
              <option value="newest">Newest First</option>
              <option value="score">Highest Score</option>
              <option value="build_time">Fastest Build</option>
            </select>
            <ArrowUpDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-zinc-500 pointer-events-none" />
          </div>
        </div>
      </div>

      {/* Stats strip */}
      <div className="mb-8 flex items-center gap-6 text-xs text-zinc-500">
        <span className="flex items-center gap-1.5">
          <TrendingUp className="h-3.5 w-3.5" /> {ideas.length} total ideas
        </span>
        <span className="flex items-center gap-1.5">
          <Bookmark className="h-3.5 w-3.5" /> {ideas.filter(i => i.is_saved).length} saved
        </span>
        <span className="flex items-center gap-1.5">
          <Filter className="h-3.5 w-3.5" /> {filteredIdeas.length} showing
        </span>
      </div>

      {/* Content */}
      {loading ? (
        <div className="py-20 flex justify-center items-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-indigo-500 border-t-transparent" />
        </div>
      ) : filteredIdeas.length === 0 ? (
        <div className="py-16 text-center glass-panel rounded-2xl border-white/5">
          {ideas.length === 0 ? (
            <>
              <TrendingUp className="h-12 w-12 text-zinc-600 mx-auto mb-4" />
              <h4 className="font-bold text-white text-lg">No SaaS Ideas Yet</h4>
              <p className="text-zinc-500 text-sm mt-1 mb-6">
                Launch the multi-agent scrapper to generate validated micro-SaaS opportunities.
              </p>
              <Link href="/dashboard/generate" className="premium-primary !min-h-10">
                <Sparkles className="h-4 w-4" /> Run Idea Engine
              </Link>
            </>
          ) : (
            <>
              <Search className="h-12 w-12 text-zinc-600 mx-auto mb-4" />
              <h4 className="font-bold text-white text-lg">No Matching Ideas</h4>
              <p className="text-zinc-500 text-sm mt-1">
                Try adjusting your search or filters.
              </p>
            </>
          )}
        </div>
      ) : (
        <div className="grid md:grid-cols-2 gap-6">
          {filteredIdeas.map(idea => (
            <div
              key={idea.id}
              className="glass-panel p-6 rounded-2xl border-white/5 hover:border-indigo-500/20 transition-all flex flex-col justify-between group"
            >
              <div>
                <div className="flex justify-between items-start gap-4">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                      Niche Score: {idea.niche_score}
                    </span>
                    <span className="flex items-center gap-1 px-2 py-0.5 rounded text-[10px] text-zinc-500 bg-zinc-800">
                      <Clock className="h-2.5 w-2.5" /> ~{idea.build_time_weeks}w
                    </span>
                  </div>
                  <button
                    onClick={() => handleSaveToggle(idea.id, idea.is_saved)}
                    className={`p-1.5 rounded-xl border border-white/5 transition-colors ${
                      idea.is_saved
                        ? "bg-amber-500/10 border-amber-500/30 text-amber-400"
                        : "text-zinc-500 hover:text-white"
                    }`}
                  >
                    <Bookmark className="h-4 w-4 fill-current" />
                  </button>
                </div>

                <h4 className="font-bold text-lg text-white mt-4">
                  Niche Target: {idea.target_user}
                </h4>
                <p className="text-zinc-400 text-xs mt-2 font-semibold uppercase tracking-wider">
                  Problem:
                </p>
                <p className="text-zinc-300 text-xs mt-1 text-justify line-clamp-3">
                  {idea.problem}
                </p>

                <p className="text-zinc-400 text-xs mt-3.5 font-semibold uppercase tracking-wider">
                  Solution:
                </p>
                <p className="text-zinc-300 text-xs mt-1 text-justify line-clamp-3">
                  {idea.solution}
                </p>
              </div>

              <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between">
                <div className="flex flex-wrap gap-1.5">
                  {idea.stack.slice(0, 4).map((t: string) => (
                    <span
                      key={t}
                      className="text-[10px] bg-zinc-800 text-zinc-400 py-0.5 px-2 rounded"
                    >
                      {t}
                    </span>
                  ))}
                  {idea.stack.length > 4 && (
                    <span className="text-[10px] text-zinc-500">
                      +{idea.stack.length - 4}
                    </span>
                  )}
                </div>
                <Link
                  href={`/dashboard/ideas/detail?id=${idea.id}`}
                  className="text-xs font-bold text-indigo-400 hover:text-indigo-300 flex items-center gap-1 opacity-70 group-hover:opacity-100 transition-opacity"
                >
                  Monetization Plan <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
